apiVersion: batch/v1
kind: Job
metadata:
  name: myjob

spec:
  template:
    metadata:
      name: testjob # Lable
    spec:
      containers:
        - name: mycont
          image: ubuntu
          command: ["/bin/bash", "-c", "echo Rahimdemy; sleep 15"]
      restartPolicy: Never # Pod should never get restarted
