apiVersion: v1
kind: PersistentVolume
metadata:
  name: myefspv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: fs-0f77acc541d548e94.efs.ca-central-1.amazonaws.com
    path: "/"
