kind: Pod
apiVersion: v1
metadata:
  name: mypod

spec:
  containers:
    - name: c00
      image: httpd
      ports:
        - containerPort: 80
      readinessProbe:
        initialDelaySeconds: 10
        httpGet:
          path: /
          port: 80
